project:
  type: website

website:
  title: "Quarto for managers"
  navbar:
    left: 
      - index.qmd
      - slides.qmd
      - set-up.qmd
      - resources.qmd 
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/StatsRhian/quarto-for-managers
          - text: Make an issue
            href:  https://github.com/StatsRhian/quarto-for-managers
  page-footer:
    center: |
      Developed by <a href="https://rhian.rbind.io/">Rhian Davies</a> ðŸŒ±. Built with <a href="https://quarto.org/">Quarto</a> ðŸ’œ.

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true



